<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Listado.aspx.cs" Inherits="WebApplication9.Listado" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link href="css/boton.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style1 {
            text-decoration: underline;
            color: #FF3300;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <span class="auto-style1"><strong>LISTADO DE PELICULAS</strong></span><br />
        <br />
        <asp:Button ID="Button1" runat="server" Text="Cargar Peliculas" OnClick="Button1_Click" />
        <br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    <Columns>
        <asp:BoundField DataField="codigo" HeaderText="Codigo" />
         <asp:BoundField DataField="nombre" HeaderText="Nombre" />
         <asp:templateField HeaderText="Imagen de Pelicula">
             <ItemTemplate>
                 <a href="Reservacion.aspx">
                    <asp:Image ID="Image1" runat="server" Width="300px" Height="300px" ImageUrl='<%#"data:Image/png;base64,"+Convert.ToBase64String ((byte [])Eval("Imagen")) %>' />
                 </a>
            </ItemTemplate>
         </asp:templateField>
        <asp:TemplateField HeaderText="IMAGEN 2">
            <ItemTemplate>
                <asp:Image ID="Image2" runat="server" Height="147px" ImageUrl='<%# "data:Image/png;base64,"+Convert.ToBase64String ((byte [])Eval("Imagen")) %>' Width="178px" />
            </ItemTemplate>
        </asp:TemplateField>
        <asp:BoundField DataField="Precio" HeaderText="PRECIO" />
        <asp:TemplateField HeaderText="Tipo Envio">
            <ItemTemplate>
                <asp:CheckBox ID="Local" runat="server" Text="Envio local" />
                <br />
                <asp:CheckBox ID="Intenacional" runat="server" Text="Internacional" />
                <br />
                <asp:Button ID="Button2" runat="server" Height="28px" Text="Mas detalles..." Width="160px" />
                <br />
                <br />
                <asp:Button ID="Button3" runat="server" Height="27px" Text="Agregar al Carrito" Width="154px" />
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Funciones">
            <ItemTemplate>
                <asp:Button ID="Button4" CssClass="button button2" runat="server" Height="28px" Text="Agregar" Width="79px" />
                <br />
                <br />
                <asp:Button ID="Button5"  CssClass="button button3" runat="server" Height="29px" Text="Borrar" Width="79px" />
                <br />
                <br />
                <asp:Button ID="Button6" CssClass="button button4" runat="server" Text="Modificar" />
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="nueva"></asp:TemplateField>
    </Columns>

            <EditRowStyle BackColor="#999999" />
            <EmptyDataTemplate>
                <asp:CheckBox ID="CheckBox1" runat="server" />
            </EmptyDataTemplate>
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />

        </asp:GridView>
    
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <asp:GridView ID="GridView2" runat="server">
        </asp:GridView>
        <br />
    
    </div>
    </form>
</body>
</html>
